# These are supported funding model platforms

github: guruh46
patreon: # Replace with a single Patreon username
open_collective: guruh46
ko_fi: guruh46
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: Guruh46
issuehunt: guruh46
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar: guruh46
buy_me_a_coffee: irawanguru4
thanks_dev: guruh46
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']

